### PR TITLE
Fix styling of API page

### LINKED ISSUE #107: Are the docs now full-width by design?
Gday @DenisCarriere 

Just had a look at the docs and on the API page they are now spanning the full-width of the page rather than having some white padding on either side, it looks like this is a result of [your commit](https://github.com/Turfjs/turf-www/commit/36f542b154b24cf48c8b034f8e27ca767726381f)

Did you do this on purpose?
alt tag

I think they look a bit more cluttered and less readable with the padding gone so are you happy for me to revert them back to have some breathing space?

### PR DESCRIPTION
**Pull request by rowanwins**
- Fixed styling of API page (to Resolve #107 )
- Fixed windows bug with getNpmPath
- Removed popup on feature if there are no feature properties

### CODE REVIEW

File: template/turf_2017/index.js [hunk 1]
```diff
@@ -47,8 +47,10 @@ module.exports = function (comments, options, callback) {
         return hljs.fixMarkup(string);
       },
       getNpmPath: function (filepath) {
-        var module = filepath.match(/packages\/turf-([a-z-\d]+)/i)[1];
-        return "npm install @turf/" + module;
+        var folder = path.dirname(filepath);
+        var foldersArray = folder.split("\\");
+        var module = foldersArray[foldersArray.length-1].replace("turf-", "");
+        return "npm install @turf/" + module
```
Comment (DenisCarriere) [inline template/turf_2017/index.js]: This section was changed on purpose, lets use Regex or some kind of "No OS specific" solution for this, on a Mac or Linux this doesn't work (`folder.split('\\')` won't work).

We just need to update the Regex express to fit both OS or use the `path` module more efficiently.

Comment (DenisCarriere) [inline template/turf_2017/index.js]: image
